package org.jchlabs.gharonda.client.util;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class AutoCmpleteTextBoxHelper2 {

	public static Map<String, Map<String, List<String>>> stateCityMap = new LinkedHashMap<String, Map<String, List<String>>>();
	public static Map<String, List<String>> citySuburbMap = null;
	public static List<String> suburbs = null;

	static {
		stateCityMap.putAll(AutoCmpleteTextBoxHelper1.stateCityMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sukapı");
		suburbs.add("Ortakapı");
		suburbs.add("Yenişehir");
		suburbs.add("Bülbül");
		citySuburbMap.put("Kars", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Akyaka");
		citySuburbMap.put("Akyaka", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Arpaçay");
		citySuburbMap.put("Arpaçay", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Digor");
		suburbs.add("Dağpınar");
		citySuburbMap.put("Digor", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kağızman");
		citySuburbMap.put("Kağızman", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sarıkamış");
		suburbs.add("Karaurgan");
		citySuburbMap.put("Sarıkamış", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Selim");
		citySuburbMap.put("Selim", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Susuz");
		citySuburbMap.put("Susuz", suburbs);
		stateCityMap.put("Kars", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Akmescit");
		suburbs.add("Kuzeykent");
		suburbs.add("Cebrail");
		suburbs.add("Akkaya Yaka");
		suburbs.add("Kuzyaka Kürdeşe");
		citySuburbMap.put("Kastamonu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Abana");
		citySuburbMap.put("Abana", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ağlı");
		citySuburbMap.put("Ağlı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Araç");
		suburbs.add("Boyalı");
		suburbs.add("İğdir Samatlar");
		citySuburbMap.put("Araç", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Azdavay");
		citySuburbMap.put("Azdavay", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bozkurt");
		citySuburbMap.put("Bozkurt", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Cide");
		citySuburbMap.put("Cide", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çatalzeytin");
		citySuburbMap.put("Çatalzeytin", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Daday");
		citySuburbMap.put("Daday", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Devrekani");
		citySuburbMap.put("Devrekani", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Doğanyurt");
		citySuburbMap.put("Doğanyurt", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hanönü");
		citySuburbMap.put("Hanönü Gökçeağaç", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("İhsangazi");
		citySuburbMap.put("İhsangazi", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("İnebolu");
		citySuburbMap.put("İnebolu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Küre");
		citySuburbMap.put("Küre", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Pınarbaşı");
		citySuburbMap.put("Pınarbaşı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Seydiler");
		citySuburbMap.put("Seydiler", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Şenpazar");
		citySuburbMap.put("Şenpazar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Taşköprü");
		citySuburbMap.put("Taşköprü", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Tosya");
		citySuburbMap.put("Tosya", suburbs);
		stateCityMap.put("Kastamonu", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sanayi");
		suburbs.add("Fevziçakmak");
		suburbs.add("Yenişehir");
		suburbs.add("Yenimahalle");
		suburbs.add("Argincik");
		suburbs.add("İldem Beyazşehir");
		suburbs.add("Ebiç");
		suburbs.add("Erkilet");
		suburbs.add("Güneşli");
		suburbs.add("Kuşçu");
		suburbs.add("Mahzemin");
		suburbs.add("Yemliha");
		citySuburbMap.put("Kocasinan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kiliçaslan");
		suburbs.add("Çarşı");
		suburbs.add("Hürriyet");
		suburbs.add("Kazım Karabekir");
		suburbs.add("Şeker Keykubat");
		suburbs.add("Becen");
		suburbs.add("Gesi");
		suburbs.add("Gürpinar");
		suburbs.add("Hisarcik");
		suburbs.add("Kiranardı");
		suburbs.add("Mimarsinan");
		suburbs.add("Turan");
		suburbs.add("Büyükbürüngüz");
		suburbs.add("Argirnas");
		citySuburbMap.put("Melikgazi", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Talas");
		suburbs.add("Başakpınar");
		suburbs.add("Erciyes");
		suburbs.add("Kepez");
		suburbs.add("Kuruköprü");
		suburbs.add("Zincidere");
		citySuburbMap.put("Talas", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Akkışla");
		citySuburbMap.put("Akkışla", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bünyan");
		suburbs.add("Akmescit");
		suburbs.add("Güllüce");
		suburbs.add("Karakaya");
		citySuburbMap.put("Bünyan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Develi");
		suburbs.add("Sindelhöyük");
		suburbs.add("Taşçı  Bakırdağ");
		citySuburbMap.put("Develi", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Felahiye");
		citySuburbMap.put("Felahiye", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hacılar");
		citySuburbMap.put("Hacılar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("İncesu");
		suburbs.add("Kızılören");
		suburbs.add("Süksün");
		citySuburbMap.put("İncesu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Özvatan");
		citySuburbMap.put("Özvatan Çukur", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Pınarbaşı");
		suburbs.add("Örenşehir");
		citySuburbMap.put("Pınarbaşı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sarioğlan");
		suburbs.add("Çiftlik");
		suburbs.add("Gölova( palas)");
		citySuburbMap.put("Sarıoğlan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sarız");
		citySuburbMap.put("Sariz", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Tomarza");
		suburbs.add("Toklar");
		suburbs.add("Dadaloğlu");
		citySuburbMap.put("Tomarza", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yahyalı");
		suburbs.add("Derebağ");
		citySuburbMap.put("Yahyalı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yeşilhisar");
		citySuburbMap.put("Yeşilhisar", suburbs);
		stateCityMap.put("Kayseri", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bademlik");
		suburbs.add("Kocahıdır");
		suburbs.add("Kavaklı");
		suburbs.add("Yoğuntaş");
		suburbs.add("İnece");
		suburbs.add("Üsküp");
		citySuburbMap.put("Kırklareli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Babaeski");
		suburbs.add("Alpullu");
		suburbs.add("Büyükmandıra");
		citySuburbMap.put("Babaeski", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Demirköy");
		suburbs.add("İğneada");
		citySuburbMap.put("Demirköy", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kofçaz");
		citySuburbMap.put("Kofçaz", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Cumhuriyet");
		suburbs.add("Hürriyet");
		suburbs.add("Büyükkarıştıran");
		suburbs.add("Ahmetbey");
		suburbs.add("Evrensekiz");
		suburbs.add("Kırıkköy");
		citySuburbMap.put("Lüleburgaz", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Pehlivanköy");
		citySuburbMap.put("Pehlivanköy", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Pınarhisar");
		citySuburbMap.put("Pınarhisar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Kaynarca");
		citySuburbMap.put("Pinarhisar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Vize");
		suburbs.add("Çakılı");
		suburbs.add("Kıyıköy");
		suburbs.add("Sergen");
		citySuburbMap.put("Vize", suburbs);
		stateCityMap.put("Kırklareli", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çarşı");
		suburbs.add("Hükümet");
		suburbs.add("Özbağ");
		suburbs.add("Göllü");
		citySuburbMap.put("Kırşehir", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Akçakent");
		suburbs.add("Kösefakılı");
		citySuburbMap.put("Akçakent", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Akpınar");
		citySuburbMap.put("Akpınar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Boztepe");
		citySuburbMap.put("Boztepe", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çiçekdağı");
		suburbs.add("Köseli");
		citySuburbMap.put("Çiçekdağı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kaman");
		suburbs.add("Demirli");
		suburbs.add("Kurancili");
		citySuburbMap.put("Kaman", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Mucur");
		citySuburbMap.put("Mucur", suburbs);
		stateCityMap.put("Kırşehir", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yahyakaptan");
		suburbs.add("Yenişehir");
		suburbs.add("Malta");
		suburbs.add("Zabitan");
		suburbs.add("Tepecik");
		suburbs.add("Cedit");
		suburbs.add("Vezirçiftliği");
		suburbs.add("Alikahya");
		citySuburbMap.put("İzmit", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Karşıyaka");
		suburbs.add("Bahçecik");
		suburbs.add("Kullar");
		suburbs.add("Yeniköy");
		suburbs.add("Yuvacık");
		citySuburbMap.put("Başiskele", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çayırova");
		suburbs.add("Şekerpınar");
		citySuburbMap.put("Çayırova", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Darıca");
		suburbs.add("Sırasöğütler");
		citySuburbMap.put("Darıca", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Dilovası");
		suburbs.add("Tavşancıl");
		citySuburbMap.put("Dilovası", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Köseköy");
		suburbs.add("Maşukiye");
		suburbs.add("Suadiye");
		suburbs.add("Uzunçiftlik");
		suburbs.add("Uzuntarla");
		suburbs.add("Büyükderbent");
		suburbs.add("Eşme");
		suburbs.add("Acısu");
		suburbs.add("Sarımeşe Akmeşe");
		suburbs.add("Arslanbey");
		citySuburbMap.put("Kartepe", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gebze");
		suburbs.add("Güzeltepe");
		citySuburbMap.put("Gebze", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gölcük");
		suburbs.add("İhsaniye");
		suburbs.add("Değirmendere");
		suburbs.add("Halidere");
		suburbs.add("Ulaşlı");
		suburbs.add("Yazlık");
		suburbs.add("Hisareyn");
		citySuburbMap.put("Gölcük", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("Kandira", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Kandıra");
		citySuburbMap.put("Kandıra", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Karamürsel");
		suburbs.add("Ereğli");
		suburbs.add("Yalakdere");
		suburbs.add("Kızderbent");
		suburbs.add("Dereköy");
		suburbs.add("Akçat");
		citySuburbMap.put("Karamürsel", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Körfez");
		suburbs.add("Hereke");
		suburbs.add("Kirazlıyalı");
		suburbs.add("Yarımca");
		citySuburbMap.put("Tütünçiftlik", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Derince");
		citySuburbMap.put("Derince", suburbs);
		stateCityMap.put("Kocaeli", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Selimiye");
		suburbs.add("Mevlana");
		suburbs.add("Şems");
		suburbs.add("İsmil");
		suburbs.add("Ovakavaği");
		citySuburbMap.put("Karatay", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Aziziye");
		suburbs.add("Zafer");
		suburbs.add("Taşcami");
		suburbs.add("Selimiye");
		suburbs.add("Dere");
		suburbs.add("Mimarsinan");
		suburbs.add("Meram");
		suburbs.add("Çarıklar");
		suburbs.add("Karadiğin");
		suburbs.add("Kaşinhanı");
		citySuburbMap.put("Meram", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Zafer");
		suburbs.add("Sille");
		suburbs.add("Şems");
		suburbs.add("Nalçacı");
		suburbs.add("Fatih");
		suburbs.add("Cumhuriyet");
		suburbs.add("Aydınlık");
		suburbs.add("Hocacihan");
		suburbs.add("Bosna");
		suburbs.add("Yükselen");
		suburbs.add("Tepeköy");
		citySuburbMap.put("Selçuklu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ahırlı");
		suburbs.add("Akkise");
		citySuburbMap.put("Ahırlı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Akören");
		citySuburbMap.put("Akören", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("İstasyon");
		suburbs.add("Kuruçay");
		suburbs.add("Altuntaş");
		suburbs.add("Doğrugöz");
		suburbs.add("Çakillar");
		suburbs.add("Adsız");
		suburbs.add("Karahüyük");
		suburbs.add("Ortaköy");
		citySuburbMap.put("Akşehir", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Altınekin");
		citySuburbMap.put("Altınekin", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Beyşehir");
		suburbs.add("Doğanbey");
		suburbs.add("Üzümlü");
		suburbs.add("Huğlu");
		suburbs.add("Sadıkhacı");
		suburbs.add("Karaali");
		citySuburbMap.put("Beyşehir", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bozkır");
		suburbs.add("Sarıoğlan");
		citySuburbMap.put("Bozkır", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Cihanbeyli");
		suburbs.add("Gölyazı");
		suburbs.add("Karabağ");
		suburbs.add("Taşpınar");
		suburbs.add("Yeniceoba");
		suburbs.add("Bulduk");
		suburbs.add("Kuşça");
		suburbs.add("Gezen");
		suburbs.add("Kütükkuşağı");
		citySuburbMap.put("Cihanbeyli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çeltik");
		suburbs.add("Gökpınar");
		citySuburbMap.put("Çeltik", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çumra");
		suburbs.add("Alibeyhüyüğü");
		suburbs.add("İçeriçumra");
		suburbs.add("Karkın");
		suburbs.add("Okçu");
		citySuburbMap.put("Çumra", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Derbent");
		citySuburbMap.put("Derbent", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Derebucak");
		suburbs.add("Çamlik");
		citySuburbMap.put("Derebucak", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Doğanhisar");
		citySuburbMap.put("Doğanhisar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Emirgazi");
		suburbs.add("Demirci");
		citySuburbMap.put("Emirgazi", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("500 evler");
		suburbs.add("Aydınlar");
		suburbs.add("Belkaya");
		suburbs.add("Aziziye");
		suburbs.add("Çayhan");
		suburbs.add("Zengen");
		citySuburbMap.put("Ereğli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Güneysınır");
		citySuburbMap.put("Güneysınır", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hadim");
		suburbs.add("Dedemli");
		suburbs.add("Korualan");
		citySuburbMap.put("Hadim", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Halkapınar");
		citySuburbMap.put("Halkapınar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hüyük");
		suburbs.add("Selki");
		citySuburbMap.put("Hüyük", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ilgin");
		suburbs.add("Argıthanı");
		suburbs.add("Aşağıçiğil");
		suburbs.add("Yukarıçiğil");
		citySuburbMap.put("Ilgin", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kadınhanı");
		suburbs.add("Osmancık");
		suburbs.add("Atkanti");
		suburbs.add("Kolukısa");
		citySuburbMap.put("Kadınhanı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Karapınar");
		suburbs.add("Yeşilyurt");
		suburbs.add("Islık");
		suburbs.add("Hotamış");
		suburbs.add("Kayalı");
		citySuburbMap.put("Karapınar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kulu");
		suburbs.add("Kozanlı");
		suburbs.add("Tavşancalı");
		suburbs.add("Zincirlikuyu");
		citySuburbMap.put("Kulu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sarayönü");
		suburbs.add("Ladik");
		citySuburbMap.put("Sarayönü", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sofuhane");
		suburbs.add("Stadyum");
		citySuburbMap.put("Seydişehir", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Taşkent");
		suburbs.add("Balcılar");
		citySuburbMap.put("Taşkent", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Tuzlukçu");
		citySuburbMap.put("Tuzlukçu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yalıhüyük");
		citySuburbMap.put("Yalihüyük", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yunak");
		suburbs.add("Kuzören");
		citySuburbMap.put("Yunak", suburbs);
		stateCityMap.put("Konya", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Alipaşa");
		suburbs.add("Balıklı");
		suburbs.add("Bahçelievler");
		suburbs.add("Börekçiler");
		suburbs.add("Hamidiye");
		suburbs.add("Yoncalı Kaplıcaları");
		suburbs.add("Ağaçköy");
		suburbs.add("Okçu");
		suburbs.add("İnköyü");
		suburbs.add("Organize Sanayi");
		suburbs.add("Kirazpinar");
		suburbs.add("Aydoğdu");
		suburbs.add("Hacı Azizler");
		suburbs.add("Ilıca Kaplıcaları");
		suburbs.add("Seyitömer");
		citySuburbMap.put("Kütahya", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Altıntaş");
		citySuburbMap.put("Altıntaş", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Aslanapa");
		citySuburbMap.put("Aslanapa", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çavdarhisar");
		citySuburbMap.put("Çavdarhisar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Domaniç");
		suburbs.add("Çukurca");
		citySuburbMap.put("Domaniç", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Dumlupınar");
		citySuburbMap.put("Dumlupınar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Emet");
		citySuburbMap.put("Emet", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gediz");
		suburbs.add("Eskigediz");
		suburbs.add("Gökler");
		citySuburbMap.put("Gediz", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hisarcık");
		citySuburbMap.put("Hisarcık", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Pazarlar");
		citySuburbMap.put("Pazarlar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Simav");
		suburbs.add("Muradınlar");
		suburbs.add("Beyce");
		suburbs.add("Çitgöl");
		suburbs.add("Güney");
		suburbs.add("Kuşu");
		suburbs.add("Naşa");
		suburbs.add("Kelemyenice");
		suburbs.add("Akdağ");
		citySuburbMap.put("Simav", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Şaphane");
		citySuburbMap.put("Şaphane", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Tavşanlı");
		suburbs.add("Çukurköy");
		suburbs.add("Tepecik");
		suburbs.add("Kuruçay");
		suburbs.add("Tunçbilek");
		citySuburbMap.put("Tavşanlı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("Tunçbilek", suburbs);
		stateCityMap.put("Kütahya", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Mustafapaşa");
		suburbs.add("Selçuklu");
		suburbs.add("Beylerbaşı");
		suburbs.add("Kaynarca");
		suburbs.add("Yeşiltepe");
		suburbs.add("Çilesiz");
		suburbs.add("Hüseyinbey");
		suburbs.add("Cevherizade");
		suburbs.add("Uçbağlar");
		suburbs.add("Beydaği");
		suburbs.add("Firat");
		suburbs.add("Hanımınçiftliği Orduzu");
		suburbs.add("Yakinkent");
		suburbs.add("Dilek");
		suburbs.add("Konak");
		suburbs.add("Topsöğüt");
		citySuburbMap.put("Malatya", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Akçadağ");
		suburbs.add("Ören");
		suburbs.add("Kürecik Kepez");
		suburbs.add("Levent");
		suburbs.add("Çatyol");
		citySuburbMap.put("Akçadağ", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Arapkir");
		suburbs.add("Taşdelen");
		citySuburbMap.put("Arapkir", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Arguvan");
		suburbs.add("Çobandere Yoncalı");
		citySuburbMap.put("Arguvan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Battalgazi");
		suburbs.add("Hatunsuyu");
		citySuburbMap.put("Battalgazi", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Darende");
		suburbs.add("Ayvalı");
		suburbs.add("Balaban");
		suburbs.add("Aşağı Ulupınar");
		citySuburbMap.put("Darende", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Doğanşehir");
		suburbs.add("Polat");
		suburbs.add("Sürgü");
		suburbs.add("Erkenek");
		suburbs.add("Kurucaova");
		suburbs.add("Gövdeli");
		citySuburbMap.put("Doğanşehir", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Doğanyol");
		citySuburbMap.put("Doğanyol", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hekimhan");
		suburbs.add("Güzelyurt");
		suburbs.add("Kurşunlu");
		citySuburbMap.put("Hekimhan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kale");
		suburbs.add("Bağlıca");
		citySuburbMap.put("Kale", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kuluncak");
		citySuburbMap.put("Kuluncak", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Pötürge");
		citySuburbMap.put("Pötürge", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yazıhan");
		suburbs.add("Durucasu");
		suburbs.add("Fethiye");
		citySuburbMap.put("Yazihan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yeşilyurt");
		suburbs.add("Yakınca");
		suburbs.add("Bostanbaşı");
		suburbs.add("Gündüzbey");
		citySuburbMap.put("Yeşilyurt", suburbs);
		stateCityMap.put("Malatya", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Manisa Merkez");
		suburbs.add("Adakale");
		suburbs.add("Tevfikiye");
		suburbs.add("Sanayi");
		suburbs.add("Adnanmenderes");
		suburbs.add("Aşağıçobanisa");
		suburbs.add("Karaoğlanli");
		suburbs.add("Muradiye");
		suburbs.add("Karaağaçlı");
		citySuburbMap.put("Manisa", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ahmetli");
		citySuburbMap.put("Ahmetli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hürriyet");
		suburbs.add("İnönü");
		suburbs.add("Fevzipaşa");
		suburbs.add("Akselendi");
		suburbs.add("Beyoba");
		suburbs.add("Kayalıoğlu");
		suburbs.add("Mecidiye");
		suburbs.add("Medar");
		suburbs.add("Süleymanlı");
		suburbs.add("Zeytinliova");
		suburbs.add("Ballıca");
		suburbs.add("Dağdere");
		citySuburbMap.put("Akhisar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Alaşehir");
		suburbs.add("Kavaklıdere");
		suburbs.add("Killik");
		suburbs.add("Uluderbent");
		suburbs.add("Yeşilyurt");
		citySuburbMap.put("Alaşehir", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Demirci");
		suburbs.add("Borlu");
		citySuburbMap.put("Demirci", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gölmarmara");
		citySuburbMap.put("Gölmarmara", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gördes");
		suburbs.add("Güneşli");
		citySuburbMap.put("Gördes", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kırkağaç");
		suburbs.add("Bakır");
		suburbs.add("Karakurt");
		suburbs.add("Gelenbe");
		suburbs.add("İlyaslar");
		citySuburbMap.put("Kırkağaç", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Köprübaşı");
		citySuburbMap.put("Köprübaşı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kula");
		suburbs.add("Gökçeören");
		citySuburbMap.put("Kula", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Zafer");
		suburbs.add("Barış");
		suburbs.add("Sartmahmut");
		suburbs.add("Yilmaz");
		suburbs.add("Adala");
		suburbs.add("Durasilli");
		suburbs.add("Gökeyüp");
		suburbs.add("Taytan");
		citySuburbMap.put("Salihli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sarıgöl");
		citySuburbMap.put("Sarıgöl", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Saruhanlı");
		suburbs.add("Dilek");
		suburbs.add("Hacirahmanli");
		suburbs.add("Koldere");
		suburbs.add("Mütevelli");
		suburbs.add("Paşaköy");
		suburbs.add("Halitpaşa");
		suburbs.add("Büyükbelen");
		citySuburbMap.put("Saruhanlı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Selendi");
		citySuburbMap.put("Selendi", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Soma");
		suburbs.add("Turgutalp");
		suburbs.add("Avdan");
		suburbs.add("Cenkyeri");
		citySuburbMap.put("Soma", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sanayi");
		suburbs.add("Ergenekon");
		suburbs.add("Derbent");
		suburbs.add("Urganlı");
		citySuburbMap.put("Turgutlu", suburbs);
		stateCityMap.put("Manisa", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("İsmetpaşa");
		suburbs.add("Gazipaşa");
		suburbs.add("Hayrullah");
		suburbs.add("Mağralı");
		suburbs.add("Yenişehir");
		suburbs.add("Fatmalı");
		suburbs.add("Önsen");
		suburbs.add("Alibeyli");
		suburbs.add("Süleymanlı");
		suburbs.add("Ilıca");
		suburbs.add("Yeniköy");
		suburbs.add("Kale");
		suburbs.add("Karacasu");
		suburbs.add("Kavlaklı");
		suburbs.add("Kürtül");
		suburbs.add("Tekir");
		suburbs.add("Baydemirli");
		suburbs.add("Şahinkayası");
		suburbs.add("Döngele");
		citySuburbMap.put("Kahramanmaraş", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Afşin");
		suburbs.add("Aritaş");
		suburbs.add("Çobanbeyli");
		suburbs.add("Çoğulhan");
		suburbs.add("Tanir");
		suburbs.add("Altınelma");
		suburbs.add("Büyüktatlı");
		citySuburbMap.put("Afşin", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Andırın");
		suburbs.add("Geben");
		suburbs.add("Yeşilova Tokmaklı");
		suburbs.add("Çokak");
		citySuburbMap.put("Andırın", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çağlayancerit");
		suburbs.add("Düzbağ");
		suburbs.add("Bozlar");
		citySuburbMap.put("Çağlayancerit", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ekinözü");
		citySuburbMap.put("Ekinözü", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Elbistan");
		suburbs.add("Büyükyapalak");
		suburbs.add("Gücük");
		suburbs.add("İğdeköy");
		suburbs.add("Demircilik");
		suburbs.add("Doğanköy");
		suburbs.add("Izgın");
		suburbs.add("Karaelbistan");
		suburbs.add("Bakiş");
		suburbs.add("Söğütlü");
		citySuburbMap.put("Elbistan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Göksun");
		suburbs.add("Büyükkizilcik");
		suburbs.add("Değirmendere");
		suburbs.add("Kanlıkavak");
		suburbs.add("Ericek");
		citySuburbMap.put("Göksun", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Nurhak");
		suburbs.add("Bariş");
		suburbs.add("Yeşilkent");
		citySuburbMap.put("Nurhak", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Pazarcık");
		suburbs.add("Narlı");
		suburbs.add("Evri");
		suburbs.add("Büyüknacar");
		suburbs.add("Yumaklicerit");
		citySuburbMap.put("Pazarcık", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Türkoğlu");
		suburbs.add("Beyoğlu");
		suburbs.add("Kılılı");
		suburbs.add("Şekeroba");
		suburbs.add("Yeşilyöre");
		citySuburbMap.put("Türkoğlu", suburbs);
		stateCityMap.put("Kahramanmaraş", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("İstasyon Tugay");
		suburbs.add("Savurkapı");
		suburbs.add("Nur");
		suburbs.add("Yalım");
		suburbs.add("Ortaköy");
		suburbs.add("Kabala");
		citySuburbMap.put("Mardin", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Dargeçit");
		suburbs.add("Kılavuz");
		suburbs.add("Sümer");
		citySuburbMap.put("Dargeçit", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Derik");
		citySuburbMap.put("Derik", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kızıltepe");
		suburbs.add("Şenyurt");
		suburbs.add("Şenyurt");
		suburbs.add("Dikmen");
		suburbs.add("Gökçe");
		suburbs.add("Yüceli");
		citySuburbMap.put("Kızıltepe", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Mazıdağı");
		citySuburbMap.put("Mazıdağı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bağlar");
		suburbs.add("Gölcük");
		suburbs.add("Yolbaşı");
		suburbs.add("Gelinkaya");
		suburbs.add("Acirli");
		suburbs.add("Çavuşlu");
		suburbs.add("Söğütlü");
		suburbs.add("Şenköy");
		citySuburbMap.put("Midyat Estel", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Nusaybin");
		suburbs.add("Akarsu");
		suburbs.add("Duruca");
		suburbs.add("Girmeli");
		citySuburbMap.put("Nusaybin", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ömerli");
		citySuburbMap.put("Ömerli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Savur");
		suburbs.add("Sürgücü");
		suburbs.add("Yeşilalan");
		suburbs.add("Pınardere");
		citySuburbMap.put("Savur", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yeşilli");
		citySuburbMap.put("Yeşilli", suburbs);
		stateCityMap.put("Mardin", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Muğla Merkez");
		suburbs.add("Bayır");
		suburbs.add("Yerkesik");
		suburbs.add("Yeşilyurt");
		suburbs.add("Kafaca");
		citySuburbMap.put("Muğla", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bodrum Merkez");
		suburbs.add("Mumcular");
		suburbs.add("Turgutreis");
		suburbs.add("Ortakentyahşi");
		suburbs.add("Yalıkavak");
		suburbs.add("Bitez");
		suburbs.add("Konacik");
		suburbs.add("Gündoğan");
		suburbs.add("Göltürkbükü");
		suburbs.add("Gümüşlük Karakaya");
		suburbs.add("Yalı");
		suburbs.add("Güvercinlik");
		citySuburbMap.put("Bodrum", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Dalaman");
		citySuburbMap.put("Dalaman", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Datça");
		citySuburbMap.put("Datça", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Fethiye Merkez");
		suburbs.add("Göcek");
		suburbs.add("Karaçulha");
		suburbs.add("Eşen");
		suburbs.add("Kemer");
		suburbs.add("Seki");
		suburbs.add("Yeşilüzümlü");
		suburbs.add("Ölüdeniz");
		suburbs.add("Çamköy");
		suburbs.add("Karadere");
		suburbs.add("Çiftlik");
		suburbs.add("Kumluova");
		suburbs.add("Kadıköy");
		citySuburbMap.put("Fethiye", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kavaklıdere");
		suburbs.add("Menteşe");
		citySuburbMap.put("Kavaklıdere", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Köyceğiz");
		suburbs.add("Toparlar");
		suburbs.add("Beyobası");
		citySuburbMap.put("Köyceğiz", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Marmaris Merkez");
		suburbs.add("Armutalan");
		suburbs.add("İçmeler");
		suburbs.add("Bozburun");
		suburbs.add("Beldibi");
		citySuburbMap.put("Marmaris", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Milas Merkez");
		suburbs.add("Güllük");
		suburbs.add("Ören");
		suburbs.add("Selimiye");
		suburbs.add("Beçin");
		citySuburbMap.put("Milas", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ortaca");
		suburbs.add("Dalyan");
		citySuburbMap.put("Ortaca", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ula Merkez");
		suburbs.add("Akyaka");
		suburbs.add("Gökova");
		citySuburbMap.put("Ula", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yatağan Merkez");
		suburbs.add("Turgut");
		suburbs.add("Bozarmut");
		citySuburbMap.put("Yatağan", suburbs);
		stateCityMap.put("Muğla", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("İstasyon");
		suburbs.add("Zafer");
		suburbs.add("Karaağaçlı");
		suburbs.add("Sungu");
		suburbs.add("Kızılağaç");
		suburbs.add("Mercimekkale");
		suburbs.add("Yaygın");
		suburbs.add("Konukbekler");
		suburbs.add("Kırköy");
		suburbs.add("Serinova");
		suburbs.add("Yağcılar");
		citySuburbMap.put("Muş", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bulanık");
		suburbs.add("Rüstemgedik");
		suburbs.add("Yoncalı");
		suburbs.add("Erentepe");
		suburbs.add("Karaağıl");
		suburbs.add("Elmakaya");
		suburbs.add("Mollakent");
		suburbs.add("Uzgörür");
		suburbs.add("Yemişen");
		suburbs.add("Sarıpınar");
		citySuburbMap.put("Bulanık", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hasköy");
		suburbs.add("Düzkışla");
		citySuburbMap.put("Hasköy", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Korkut");
		suburbs.add("Altınova");
		suburbs.add("Karakale");
		citySuburbMap.put("Korkut", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Malazgirt");
		suburbs.add("Gölkoru");
		suburbs.add("Aktuzla");
		suburbs.add("Karahasan Adaksu");
		suburbs.add("Nurettin");
		citySuburbMap.put("Malazgirt", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Varto");
		suburbs.add("Çaylar");
		suburbs.add("Karaköy");
		citySuburbMap.put("Varto", suburbs);
		stateCityMap.put("Muş", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Nevşehir Merkez");
		suburbs.add("Siteler");
		suburbs.add("Eskisanayi");
		suburbs.add("Camicedit");
		suburbs.add("Afet Evleri");
		suburbs.add("Çat");
		suburbs.add("Göre");
		suburbs.add("Kavak");
		suburbs.add("Kaymaklı");
		suburbs.add("Narköy");
		suburbs.add("Sulusaray");
		suburbs.add("Uçhisar");
		citySuburbMap.put("Nevşehir", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Acıgöl");
		suburbs.add("Karapınar");
		suburbs.add("Tatların");
		citySuburbMap.put("Acıgöl", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Avanos");
		suburbs.add("Özkonak");
		suburbs.add("Çaliş");
		suburbs.add("Kalaba");
		citySuburbMap.put("Avanos", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Derinkuyu");
		suburbs.add("Yazıhöyük");
		citySuburbMap.put("Derinkuyu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gülşehir");
		suburbs.add("Karacaşar");
		suburbs.add("Tuzköy");
		citySuburbMap.put("Gülşehir", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hacıbektaş");
		citySuburbMap.put("Hacıbektaş", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kozaklı");
		citySuburbMap.put("Kozaklı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ürgüp");
		suburbs.add("Ortahisar");
		suburbs.add("Başdere");
		citySuburbMap.put("Ürgüp", suburbs);
		stateCityMap.put("Nevşehir", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Niğde Merkez");
		suburbs.add("Sungurbey");
		suburbs.add("Afetevleri");
		suburbs.add("Değirmenli");
		suburbs.add("Dündarlı");
		suburbs.add("Edikli");
		suburbs.add("Gümüşler");
		suburbs.add("Hacıabdullah");
		suburbs.add("Yıldıztepe");
		suburbs.add("Karaatlı");
		suburbs.add("Sazlica");
		suburbs.add("Yeşilgölcük");
		suburbs.add("Alay");
		suburbs.add("Bağlama");
		suburbs.add("Konakli");
		suburbs.add("Orhanli");
		suburbs.add("Fertek şube");
		suburbs.add("Aktaş");
		suburbs.add("Kiledere");
		citySuburbMap.put("Niğde", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Altunhisar");
		suburbs.add("Yakacık");
		suburbs.add("Karakapı");
		suburbs.add("Keçikalesi");
		citySuburbMap.put("Altunhisar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bor");
		suburbs.add("Kemerhisar");
		suburbs.add("Bahçeli");
		suburbs.add("Çukurkuyu");
		citySuburbMap.put("Bor", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çamardı");
		suburbs.add("Burç");
		citySuburbMap.put("Çamardı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Özyurt");
		suburbs.add("Azatli");
		suburbs.add("Bozköy");
		suburbs.add("Divarlı");
		citySuburbMap.put("Çiftlik Özyurt", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ulukışla");
		suburbs.add("Darboğaz");
		citySuburbMap.put("Ulukışla", suburbs);
		stateCityMap.put("Niğde", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Ordu Merkez");
		suburbs.add("Kumbaşı");
		suburbs.add("Bahcelievler");
		citySuburbMap.put("Ordu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Akkuş");
		suburbs.add("Salman");
		suburbs.add("Akpınar");
		suburbs.add("Yenikonak");
		citySuburbMap.put("Akkuş", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Aybastı");
		suburbs.add("Alacalar");
		suburbs.add("Çakırlı");
		citySuburbMap.put("Aybastı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çamaş");
		citySuburbMap.put("Çamaş", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çatalpınar");
		suburbs.add("Göller");
		citySuburbMap.put("Çatalpınar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çaybaşı");
		citySuburbMap.put("Çaybaşı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Fatsa");
		suburbs.add("Ilıca");
		suburbs.add("Bolaman");
		suburbs.add("Aslancami");
		suburbs.add("Hatipli");
		citySuburbMap.put("Fatsa", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gölköy");
		suburbs.add("Aydoğan");
		suburbs.add("Damarlı");
		suburbs.add("Düzyayla");
		suburbs.add("Güzelyurt");
		citySuburbMap.put("Gölköy", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gülyalı");
		citySuburbMap.put("Gülyalı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gürgentepe");
		suburbs.add("Işiktepe");
		citySuburbMap.put("Gürgentepe", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("İkizce");
		suburbs.add("Şenbolluk");
		suburbs.add("Yoğunoluk");
		citySuburbMap.put("İkizce", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kabadüz");
		citySuburbMap.put("Karadüz", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kabataş");
		citySuburbMap.put("Kabataş", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Korgan");
		suburbs.add("Çamlı");
		suburbs.add("Çiftlik");
		suburbs.add("Tepealan");
		citySuburbMap.put("Korgan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kumru");
		suburbs.add("Fizme");
		citySuburbMap.put("Kumru", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Mesudiye");
		citySuburbMap.put("Mesudiye", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Perşembe");
		suburbs.add("Medreseönü");
		citySuburbMap.put("Perşembe", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ulubey");
		citySuburbMap.put("Ulubey", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ünye");
		suburbs.add("Tekkiraz");
		suburbs.add("Pelitliyatak");
		suburbs.add("İnkur");
		suburbs.add("Erenyurt");
		suburbs.add("Fahih");
		citySuburbMap.put("Ünye", suburbs);
		stateCityMap.put("Ordu", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Rıze Merkez");
		suburbs.add("Vilayet");
		suburbs.add("Kazimkarabekir");
		suburbs.add("Gündoğdu");
		suburbs.add("Çaykent");
		citySuburbMap.put("Rize", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ardeşen");
		suburbs.add("Tunca");
		citySuburbMap.put("Ardeşen", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çamlıhemşin");
		citySuburbMap.put("Çamlıhemşin", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çayeli");
		suburbs.add("Madenli");
		suburbs.add("Büyükköy");
		suburbs.add("Kaptanpaşa");
		citySuburbMap.put("Çayeli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Derepazarı");
		citySuburbMap.put("Derepazarı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Fındıklı");
		citySuburbMap.put("Fındıklı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Güneysu");
		citySuburbMap.put("Güneysu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hemşin");
		citySuburbMap.put("Hemşin", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("İkizdere");
		citySuburbMap.put("Ikizdere", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("İyidere");
		suburbs.add("Kendirli");
		citySuburbMap.put("İkizdere", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kalkandere");
		citySuburbMap.put("Kalkandere", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Pazar");
		citySuburbMap.put("Pazar", suburbs);
		stateCityMap.put("Rize", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Adapazarı Merkez");
		suburbs.add("Semerciler");
		suburbs.add("İstiklal");
		suburbs.add("Tığcılar");
		suburbs.add("Tepekum");
		suburbs.add("Karaosman");
		suburbs.add("Karaman");
		citySuburbMap.put("Adapazarı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hendek");
		suburbs.add("Yeşilyurt");
		citySuburbMap.put("Hendek", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Arifiye");
		suburbs.add("Hanlı");
		suburbs.add("Nehirkent");
		citySuburbMap.put("Arifiye", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Erenler");
		suburbs.add("Bekirpaşa");
		suburbs.add("Çaybaşıyeniköy");
		citySuburbMap.put("Erenler", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Serdivan");
		suburbs.add("Kazımpaşa");
		suburbs.add("Yazlık");
		suburbs.add("Beşköprü");
		citySuburbMap.put("Serdivan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Akyazı Merkez");
		suburbs.add("Küçücek");
		suburbs.add("Dokurcun");
		suburbs.add("Altındere");
		suburbs.add("Kuzuluk");
		citySuburbMap.put("Akyazı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ferizli");
		citySuburbMap.put("Ferizli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Geyve");
		suburbs.add("Alifuatpaşa");
		citySuburbMap.put("Geyve", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Karapürçek");
		citySuburbMap.put("Karapürçek", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Karasu");
		suburbs.add("Limandere");
		citySuburbMap.put("Karasu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kaynarca");
		citySuburbMap.put("Kaynarca", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kocaali");
		suburbs.add("Ortaköy");
		citySuburbMap.put("Kocaali", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Pamukova");
		citySuburbMap.put("Pamukova", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sapanca");
		suburbs.add("Kırkpınar");
		suburbs.add("Kurtköy");
		citySuburbMap.put("Sapanca", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Söğütlü");
		citySuburbMap.put("Söğütlü", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Taraklı");
		citySuburbMap.put("Taraklı", suburbs);
		stateCityMap.put("Sakarya", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Atakum");
		suburbs.add("Kurupelit");
		suburbs.add("Altınkum");
		suburbs.add("Atakent");
		suburbs.add("Çatalçam");
		suburbs.add("Taflan");
		citySuburbMap.put("Atakum", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kökçüoğlu");
		suburbs.add("19-May");
		suburbs.add("Hastanebaşi");
		suburbs.add("Cedit");
		suburbs.add("Gazi");
		suburbs.add("Rasathane");
		suburbs.add("İstasyon");
		suburbs.add("Yeşilkent");
		citySuburbMap.put("İlkadım", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Canik");
		citySuburbMap.put("Canik", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Tekkeköy");
		suburbs.add("Aşağıçinik");
		suburbs.add("Kutlukent");
		suburbs.add("Büyüklü");
		citySuburbMap.put("Tekkeköy", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Alaçam");
		citySuburbMap.put("Alaçam", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Asarcık");
		citySuburbMap.put("Asarcık", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ayvacık");
		citySuburbMap.put("Ayvacık", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bahçeler");
		suburbs.add("Çarşı");
		suburbs.add("Çetinkaya");
		suburbs.add("Doğanca");
		citySuburbMap.put("Bafra", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çarşamba");
		suburbs.add("Dikbıyık");
		suburbs.add("Çınarlık");
		suburbs.add("Hürriyet");
		suburbs.add("Ağcagüney");
		citySuburbMap.put("Çarşamba", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Havza");
		citySuburbMap.put("Havza", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kavak");
		citySuburbMap.put("Kavak", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ladik");
		citySuburbMap.put("Ladik", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ballica");
		suburbs.add("Dereköy");
		suburbs.add("Yörükler");
		citySuburbMap.put("19 Mayıs Ballıca", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Salıpazarı");
		citySuburbMap.put("Salıpazarı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Terme");
		suburbs.add("Bazlamaç");
		suburbs.add("Evci");
		suburbs.add("Sakarlı");
		suburbs.add("Hüseyinmescidi");
		suburbs.add("Söğütlü");
		suburbs.add("Kozluk");
		citySuburbMap.put("Terme", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Vezirköprü");
		suburbs.add("Gölköy");
		suburbs.add("Narlısaray");
		citySuburbMap.put("Vezirköprü", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yakakent");
		citySuburbMap.put("Yakakent", suburbs);
		stateCityMap.put("Samsun", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Siirt");
		citySuburbMap.put("Siirt", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Baykan");
		suburbs.add("Ziyaret");
		citySuburbMap.put("Baykan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Eruh");
		citySuburbMap.put("Eruh", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kurtalan");
		suburbs.add("Kayabağlar");
		citySuburbMap.put("Kurtalan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Pervari");
		citySuburbMap.put("Pervari", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Aydınlar");
		citySuburbMap.put("Aydınlar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Şirvan");
		citySuburbMap.put("Şirvan", suburbs);
		stateCityMap.put("Siirt", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sinop");
		suburbs.add("Kabal");
		citySuburbMap.put("Sinop", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ayancik");
		suburbs.add("Yenikonak");
		citySuburbMap.put("Ayancık", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Boyabat");
		citySuburbMap.put("Boyabat", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Dikmen");
		citySuburbMap.put("Dikmen", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Durağan");
		suburbs.add("Çerçiler");
		citySuburbMap.put("Durağan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Erfelek");
		citySuburbMap.put("Erfelek", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gerze");
		citySuburbMap.put("Gerze", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Saraydüzü");
		citySuburbMap.put("Saraydüzü", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Türkeli");
		citySuburbMap.put("Türkeli", suburbs);
		stateCityMap.put("Sinop", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Mimarsinan");
		suburbs.add("Kümbet");
		suburbs.add("Çarşı");
		suburbs.add("Aydoğan");
		suburbs.add("Gökçebostan");
		suburbs.add("Ferhatbostan");
		suburbs.add("Kale");
		suburbs.add("Toptancılar Sitesi");
		suburbs.add("Cumhuriyetüniversitesi");
		suburbs.add("Kurtlapa");
		suburbs.add("Yakupoğlan");
		suburbs.add("Yıldız");
		citySuburbMap.put("Sivas", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Akıncılar");
		citySuburbMap.put("Akıncılar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Altınyayla");
		citySuburbMap.put("Altınyayla", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Divriği");
		citySuburbMap.put("Divriği", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Doğanşar");
		citySuburbMap.put("Doğanşar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gemerek");
		suburbs.add("Sizir");
		suburbs.add("Yeniçubuk");
		citySuburbMap.put("Gemerek", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gölova");
		citySuburbMap.put("Gölova", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gürün");
		citySuburbMap.put("Gürün", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hafik");
		citySuburbMap.put("Hafik", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("İmranli");
		citySuburbMap.put("İmranli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kangal");
		suburbs.add("Alacahan");
		suburbs.add("Çetinkaya");
		citySuburbMap.put("Kangal", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Koyulhisar");
		citySuburbMap.put("Koyulhisar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Suşehri");
		citySuburbMap.put("Suşehri", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Şarkışla");
		citySuburbMap.put("Şarkışla", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ulaş");
		citySuburbMap.put("Ulaş", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yildizeli");
		suburbs.add("Güneykaya");
		suburbs.add("Yavu");
		citySuburbMap.put("Yıldızeli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Zara");
		citySuburbMap.put("Zara", suburbs);
		stateCityMap.put("Sivas", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Tekirdağ Merkez");
		suburbs.add("Eskicami");
		suburbs.add("Altınova");
		suburbs.add("Aydoğdu");
		suburbs.add("Karacakılavuz");
		suburbs.add("Barbaros");
		suburbs.add("Inecik");
		citySuburbMap.put("Tekirdağ", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çerkezköy");
		suburbs.add("Kapaklı");
		suburbs.add("Kızılpınar");
		suburbs.add("Karaağaç");
		suburbs.add("Veliköy");
		citySuburbMap.put("Çerkezköy", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sanayi");
		suburbs.add("Silahtar");
		suburbs.add("Velimeşe");
		suburbs.add("Marmaracık");
		suburbs.add("Misinli");
		suburbs.add("Ulaş");
		citySuburbMap.put("Çorlu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hayrabolu");
		suburbs.add("Çerkezmüsellim");
		citySuburbMap.put("Hayrabolu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Malkara");
		suburbs.add("Sağlamtaş");
		citySuburbMap.put("Malkara", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Marmaraereğlisi");
		suburbs.add("Yeniçiftlik Sahil");
		suburbs.add("Sultanköy");
		citySuburbMap.put("Marmaraereğlisi", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Muratlı");
		citySuburbMap.put("Muratlı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Saray");
		suburbs.add("Büyükyoncalı");
		suburbs.add("Beyazköy");
		citySuburbMap.put("Saray", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Şarköy");
		suburbs.add("Mürefte");
		suburbs.add("Hoşköy");
		citySuburbMap.put("Şarköy", suburbs);
		stateCityMap.put("Tekirdağ", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Perakende");
		suburbs.add("Bedestenlioglu");
		suburbs.add("Karşıyaka");
		suburbs.add("Çat");
		suburbs.add("Çamlıbel");
		suburbs.add("Gökdere");
		suburbs.add("Emirseyit");
		suburbs.add("Güryildiz");
		citySuburbMap.put("Tokat", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Almus");
		suburbs.add("Çevreli");
		suburbs.add("Ormandibi");
		citySuburbMap.put("Almus", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Artova");
		citySuburbMap.put("Artova", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Başçiftlik");
		citySuburbMap.put("Başçiftlik", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Erbaa");
		suburbs.add("Doğanyurt");
		suburbs.add("Karayaka");
		suburbs.add("Kozlu");
		suburbs.add("Gökal");
		citySuburbMap.put("Erbaa", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Niksar");
		suburbs.add("Yazicik");
		suburbs.add("Ardiçli");
		suburbs.add("Yolkonak");
		citySuburbMap.put("Niksar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Pazar");
		suburbs.add("Üzümören");
		citySuburbMap.put("Pazar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Reşadiye");
		suburbs.add("Baydarli");
		suburbs.add("Hasanşeyh");
		suburbs.add("Bereketli");
		suburbs.add("Bozçali");
		citySuburbMap.put("Reşadiye", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sulusaray");
		suburbs.add("Dutluca");
		citySuburbMap.put("Sulusaray", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Turhal");
		suburbs.add("Şenyurt");
		suburbs.add("Dökmetepe");
		suburbs.add("Yenisu");
		citySuburbMap.put("Turhal", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yeşilyurt");
		citySuburbMap.put("Yeşilyurt", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Zile");
		suburbs.add("Evrenköy");
		suburbs.add("İğdir");
		suburbs.add("Güzelyazı");
		citySuburbMap.put("Zile", suburbs);
		stateCityMap.put("Tokat", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Trabzon Merkez");
		suburbs.add("Erdoğdu");
		suburbs.add("Beşirli");
		suburbs.add("Sanayi");
		suburbs.add("Çarşı");
		suburbs.add("Bostancı");
		suburbs.add("Pelitli");
		suburbs.add("Akoluk");
		suburbs.add("Akyazı");
		suburbs.add("Çukurçayir");
		suburbs.add("Yalıncak");
		suburbs.add("Çağlayan");
		suburbs.add("Akçaköy");
		citySuburbMap.put("Trabzon", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Akçaabat");
		suburbs.add("Doğanköy");
		suburbs.add("Işıklar");
		suburbs.add("Derecik");
		suburbs.add("Akçaköy");
		suburbs.add("Akçakale");
		suburbs.add("Akpınar");
		suburbs.add("Darıca");
		suburbs.add("Kavaklı");
		suburbs.add("Mersin");
		suburbs.add("Söğütlü");
		suburbs.add("Yıldızlı");
		suburbs.add("Dörtyol");
		citySuburbMap.put("Akçaabat", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Arakli");
		suburbs.add("Dağbaşi");
		suburbs.add("Erenler");
		suburbs.add("Yeşilyurt");
		citySuburbMap.put("Araklı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Arsin");
		suburbs.add("Yeşilyalı");
		citySuburbMap.put("Arsin", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Beşikdüzü");
		citySuburbMap.put("Beşikdüzü", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çarşıbaşı");
		citySuburbMap.put("Çarşibaşi", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çaykara");
		suburbs.add("Karaçam");
		citySuburbMap.put("Çaykara", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Dernekpazarı");
		citySuburbMap.put("Dernekpazarı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Düzköy");
		suburbs.add("Çalköy");
		suburbs.add("Çayırbağı");
		citySuburbMap.put("Düzköy", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hayrat");
		citySuburbMap.put("Hayrat", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Köprübaşı");
		suburbs.add("Beşköy");
		citySuburbMap.put("Köprübaşı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Maçka");
		suburbs.add("Esiroğlu");
		suburbs.add("Atasu");
		citySuburbMap.put("Maçka", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Of");
		suburbs.add("Bölümlü");
		suburbs.add("Kıyıcık");
		suburbs.add("Uğurlu");
		citySuburbMap.put("Of", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sürmene");
		citySuburbMap.put("Sürmene", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Şalpazarı");
		suburbs.add("Geyikli");
		citySuburbMap.put("Şalpazarı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Tonya");
		citySuburbMap.put("Tonya", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Vakfıkebir");
		suburbs.add("Yalıköy");
		citySuburbMap.put("Vakfikebir", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yomra");
		suburbs.add("Kaşüstü");
		suburbs.add("Özdil");
		suburbs.add("Oymalı");
		citySuburbMap.put("Yomra", suburbs);
		stateCityMap.put("Trabzon", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Tunceli");
		suburbs.add("Çiçekli");
		suburbs.add("Kocakoç");
		suburbs.add("Sütlüce");
		citySuburbMap.put("Tunceli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çemişgezek");
		suburbs.add("Akçapınar");
		suburbs.add("Gedikler");
		citySuburbMap.put("Çemişgezek", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hozat");
		citySuburbMap.put("Hozat", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Mazgirt");
		suburbs.add("Akpazar");
		citySuburbMap.put("Mazgirt", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Nazimiye");
		suburbs.add("Büyükyurt");
		citySuburbMap.put("Nazimiye", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ovacık");
		suburbs.add("Yeşilyaz");
		citySuburbMap.put("Ovacık", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Pertek");
		suburbs.add("Akdemir");
		suburbs.add("Dere");
		suburbs.add("Pınarlar");
		citySuburbMap.put("Pertek", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Pülümür");
		suburbs.add("Kırmızıköprü");
		citySuburbMap.put("Pülümür", suburbs);
		stateCityMap.put("Tunceli", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sanayi");
		suburbs.add("Selçuklu");
		suburbs.add("Direkli");
		suburbs.add("Valilik");
		suburbs.add("Çarşi");
		suburbs.add("Hamidiye");
		suburbs.add("Kısas");
		suburbs.add("Uğurlu");
		citySuburbMap.put("Şanlıurfa", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Akçakale");
		suburbs.add("Pekmezli");
		citySuburbMap.put("Akçakale", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Birecik");
		suburbs.add("Ayran");
		suburbs.add("Mezra");
		citySuburbMap.put("Birecik", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bozova");
		suburbs.add("Yaylak");
		suburbs.add("Yaslica");
		citySuburbMap.put("Bozova", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ceylanpınar");
		citySuburbMap.put("Ceylanpinar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Halfeti");
		suburbs.add("Yukarıgöklü");
		suburbs.add("Argil");
		citySuburbMap.put("Halfeti", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Harran");
		citySuburbMap.put("Harran", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gölcük");
		citySuburbMap.put("Hilvan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Siverek");
		suburbs.add("Gürakar");
		suburbs.add("Kapıkaya");
		citySuburbMap.put("Siverek", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Suruç");
		suburbs.add("Onbirnisan");
		citySuburbMap.put("Suruç", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Viranşehir");
		citySuburbMap.put("Viranşehir", suburbs);
		stateCityMap.put("Şanlıurfa", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Aybey");
		suburbs.add("Yenisanayi");
		suburbs.add("Dokumacilar");
		suburbs.add("İlyaslı");
		suburbs.add("Bölme");
		citySuburbMap.put("Uşak", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Banaz");
		suburbs.add("Kızılcasöğüt");
		citySuburbMap.put("Banaz", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Eşme");
		suburbs.add("Yeleğen");
		citySuburbMap.put("Eşme", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Karahallı");
		citySuburbMap.put("Karahalli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sivaslı");
		suburbs.add("Tatar");
		suburbs.add("Selçikler");
		suburbs.add("Pınarbaşı");
		suburbs.add("Yayalar");
		citySuburbMap.put("Sivaslı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ulubey");
		citySuburbMap.put("Ulubey", suburbs);
		stateCityMap.put("Uşak", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Van Merkez");
		suburbs.add("İskele");
		suburbs.add("Valimithatbey");
		suburbs.add("İstasyon");
		suburbs.add("Suphan");
		suburbs.add("Bostaniçi");
		citySuburbMap.put("Van", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bahçesaray");
		citySuburbMap.put("Bahçesaray", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Başkale");
		citySuburbMap.put("Başkale", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çaldıran");
		citySuburbMap.put("Çaldıran", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çatak");
		citySuburbMap.put("Çatak", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Edremit");
		suburbs.add("Çiçekli");
		citySuburbMap.put("Edremit", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Erciş");
		suburbs.add("Çelebibağ");
		suburbs.add("Kocapınar");
		citySuburbMap.put("Erciş", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gevaş");
		suburbs.add("Uysal");
		citySuburbMap.put("Gevaş", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gürpınar");
		suburbs.add("Güzelsu");
		suburbs.add("Yalınca");
		suburbs.add("Kırkgeçit");
		citySuburbMap.put("Gürpinar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Muradiye");
		suburbs.add("Unseli");
		citySuburbMap.put("Muradiye", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Özalp");
		suburbs.add("Sağmalı");
		suburbs.add("Dorutay");
		citySuburbMap.put("Özalp", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Saray");
		citySuburbMap.put("Saray", suburbs);
		stateCityMap.put("Van", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Yozgat Merkez");
		suburbs.add("Terminal");
		suburbs.add("Bahçeşehir");
		citySuburbMap.put("Yozgat", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Akdağmadeni");
		suburbs.add("Oluközü");
		suburbs.add("Umutlu");
		suburbs.add("Belekçahan");
		citySuburbMap.put("Akdağmadeni", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Aydıncık");
		suburbs.add("Kazankaya");
		suburbs.add("Baydiğin");
		citySuburbMap.put("Aydıncık", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Boğazlıyan");
		suburbs.add("Yamaçlı");
		citySuburbMap.put("Boğazlıyan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çandır");
		citySuburbMap.put("Çandır", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çayıralan");
		suburbs.add("Konuklar");
		suburbs.add("Curali");
		citySuburbMap.put("Çayıralan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Çokradan");
		citySuburbMap.put("Çayiralan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çekerek");
		citySuburbMap.put("Çekerek", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kadışehri");
		suburbs.add("Haliköy");
		citySuburbMap.put("Kadışehri", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Saraykent");
		suburbs.add("Ozan");
		citySuburbMap.put("Saraykent", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sarıkaya");
		suburbs.add("Babayağmur");
		suburbs.add("Karayakup");
		suburbs.add("Yukarısarıkaya");
		citySuburbMap.put("Sarıkaya", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sorgun");
		suburbs.add("Bahadin");
		suburbs.add("Çiğdemli");
		suburbs.add("Doğankent");
		suburbs.add("Eymir");
		suburbs.add("Araplı");
		suburbs.add("Belencumafakılı");
		citySuburbMap.put("Sorgun", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Şefaatli");
		citySuburbMap.put("Şefaatli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yenifakılı");
		citySuburbMap.put("Yenifakılı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yerköy");
		suburbs.add("Sarayköy");
		citySuburbMap.put("Yerköy", suburbs);
		stateCityMap.put("Yozgat", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Zonguldak Merkez");
		suburbs.add("Yeniçarşı");
		suburbs.add("Rüzgarlımeşe");
		suburbs.add("Ikincimakas");
		suburbs.add("Soğuksu");
		suburbs.add("Beycuma");
		suburbs.add("Kilimli");
		suburbs.add("Çatalağzı");
		suburbs.add("Kozlu");
		suburbs.add("Gelik");
		suburbs.add("Muslu");
		suburbs.add("Elvanpazarcık");
		suburbs.add("Karaman");
		citySuburbMap.put("Zonguldak", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Alaplı");
		suburbs.add("Gümeli");
		citySuburbMap.put("Alaplı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çaycuma");
		suburbs.add("Filyos Hisarönü");
		suburbs.add("Perşembe");
		suburbs.add("Saltukova");
		suburbs.add("Karapınar");
		suburbs.add("Kızılbel");
		suburbs.add("Muharremşah");
		suburbs.add("Nebioğlu");
		citySuburbMap.put("Çaycuma", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Devrek");
		suburbs.add("Eğerci");
		suburbs.add("Çaydeğirmeni");
		citySuburbMap.put("Devrek", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bağlık");
		suburbs.add("Meydanbaşı");
		suburbs.add("Armutcuk");
		suburbs.add("Gülüç");
		suburbs.add("Ormanlı");
		suburbs.add("Gökçeler");
		citySuburbMap.put("Karadenizereğli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gökçebey");
		suburbs.add("Bakacakkadi");
		citySuburbMap.put("Gökçebey", suburbs);
		stateCityMap.put("Zonguldak", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Aksaray Merkez");
		suburbs.add("Çarşı");
		suburbs.add("Sanayi");
		suburbs.add("Bağlıkaya");
		suburbs.add("Topakkaya");
		suburbs.add("Sultanhanı");
		suburbs.add("Taşpınar");
		suburbs.add("Helvadere");
		suburbs.add("İncesu");
		suburbs.add("Yeşilova");
		suburbs.add("Yenikent");
		suburbs.add("Yeşiltepe");
		suburbs.add("Aratol");
		suburbs.add("Hanobası");
		suburbs.add("Hamidiye");
		suburbs.add("Karkın");
		suburbs.add("Kutlu");
		suburbs.add("Sağlık");
		suburbs.add("Altınkaya");
		suburbs.add("Beyazsaray");
		citySuburbMap.put("Aksaray", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ağaçören");
		citySuburbMap.put("Ağaçören", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Eskil");
		suburbs.add("Eşmekaya");
		citySuburbMap.put("Eskil", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ağaçlı");
		suburbs.add("Demirci");
		citySuburbMap.put("Gülağaç", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Gülpınar");
		citySuburbMap.put("Gülağaç,", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Güzelyurt");
		suburbs.add("Ihlara");
		suburbs.add("Selime");
		citySuburbMap.put("Güzelyurt", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ortaköy");
		suburbs.add("Harmandalı");
		suburbs.add("Balcı");
		suburbs.add("Sarıkaraman");
		citySuburbMap.put("Ortaköy", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sarıyahşi");
		citySuburbMap.put("Sarıyahşi", suburbs);
		stateCityMap.put("Aksaray", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bayburt");
		suburbs.add("Maden");
		citySuburbMap.put("Bayburt", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Aydıntepe");
		citySuburbMap.put("Aydıntepe", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Demirözü");
		suburbs.add("Gökçedere");
		citySuburbMap.put("Demirözü", suburbs);
		stateCityMap.put("Bayburt", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Cedit");
		suburbs.add("İmaret");
		suburbs.add("Akçaşehir");
		suburbs.add("Sudurağı");
		citySuburbMap.put("Karaman", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ayrancı");
		citySuburbMap.put("Ayrancı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kazımkarabekir");
		citySuburbMap.put("Başyayla", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ermenek");
		suburbs.add("Güneyyurt");
		suburbs.add("Kazancı");
		citySuburbMap.put("Ermenek", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sarıveliler");
		suburbs.add("Göktepe");
		citySuburbMap.put("Kazımkarabekir", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Başyayla");
		citySuburbMap.put("Sarıveliler", suburbs);
		stateCityMap.put("Karaman", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Fabrikalar");
		suburbs.add("Tepebaşi");
		suburbs.add("Yuva");
		suburbs.add("Sanayi");
		suburbs.add("Aşağımahmutlar");
		suburbs.add("Hacilar");
		citySuburbMap.put("Kırıkkale", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bahşili");
		citySuburbMap.put("Bahşili", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Balişeyh");
		citySuburbMap.put("Balişeyh", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çelebi");
		citySuburbMap.put("Çelebi", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Delice");
		suburbs.add("Çerikli");
		citySuburbMap.put("Delice", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Karakeçili");
		citySuburbMap.put("Karakeçili", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Keskin");
		citySuburbMap.put("Keskin", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sulakyurt");
		citySuburbMap.put("Sulakyurt", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yahşihan");
		citySuburbMap.put("Yahşihan", suburbs);
		stateCityMap.put("Kırıkkale", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Petrol");
		suburbs.add("Çarşı");
		suburbs.add("Kültür");
		suburbs.add("Gap");
		suburbs.add("Balpınar");
		citySuburbMap.put("Batman", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Beşiri");
		suburbs.add("Beşpinar");
		suburbs.add("Beyçayiri");
		suburbs.add("Oğuz");
		suburbs.add("İkiköprü");
		citySuburbMap.put("Beşiri", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Gercüş");
		suburbs.add("Kayapinar");
		citySuburbMap.put("Gercüş", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hasankeyf");
		citySuburbMap.put("Hasankeyf", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kozluk");
		suburbs.add("Bekirhan");
		suburbs.add("Tuzlagöze");
		citySuburbMap.put("Kozluk", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sason");
		citySuburbMap.put("Sason", suburbs);
		stateCityMap.put("Batman", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Şırnak");
		suburbs.add("Kızılsu");
		suburbs.add("Balveren");
		suburbs.add("Kasrik");
		suburbs.add("Kumçatı");
		citySuburbMap.put("Şırnak", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Beytüşşebap");
		suburbs.add("Mezra");
		citySuburbMap.put("Beytüşşebap", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Cizre");
		suburbs.add("Dicle");
		suburbs.add("Kocapınar");
		citySuburbMap.put("Cizre", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Güçlükonak");
		citySuburbMap.put("Güçlükonak", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("İdil");
		suburbs.add("Haberli");
		suburbs.add("Oyalı");
		suburbs.add("Sirtköy");
		suburbs.add("Karalar");
		citySuburbMap.put("İdil", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Silopi");
		suburbs.add("Çalişkan");
		suburbs.add("Görümlü");
		suburbs.add("Başverimli");
		citySuburbMap.put("Silopi", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Uludere");
		suburbs.add("Hilal");
		suburbs.add("Ortabağ");
		suburbs.add("Şenoba");
		suburbs.add("Uzungeçit");
		citySuburbMap.put("Uludere", suburbs);
		stateCityMap.put("Şırnak", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Demirciler");
		suburbs.add("Yenisanayi");
		suburbs.add("Arit");
		suburbs.add("Kozcağız");
		suburbs.add("Hasankadı");
		citySuburbMap.put("Bartın", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Amasra");
		citySuburbMap.put("Amasra", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kurucaşile");
		citySuburbMap.put("Kurucaşile", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ulus");
		suburbs.add("Kumluca");
		suburbs.add("Abdipaşa");
		citySuburbMap.put("Ulus", suburbs);
		stateCityMap.put("Bartın", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ardahan");
		suburbs.add("Hasköy");
		suburbs.add("Yalnızçam");
		citySuburbMap.put("Ardahan", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çıldır");
		suburbs.add("Doğruyol");
		suburbs.add("Kurtkale");
		citySuburbMap.put("Çıldır", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Damal");
		citySuburbMap.put("Damal", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Göle");
		suburbs.add("Çayırbaşı");
		citySuburbMap.put("Göle", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hanak");
		citySuburbMap.put("Hanak", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Posof");
		citySuburbMap.put("Posof", suburbs);
		stateCityMap.put("Ardahan", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Iğdır");
		suburbs.add("Melekli");
		suburbs.add("Halfeli");
		suburbs.add("Hoşhaber");
		citySuburbMap.put("Iğdır", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Aralık");
		citySuburbMap.put("Aralık", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Karakoyunlu");
		suburbs.add("Taşburun");
		citySuburbMap.put("Karakoyunlu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Tuzluca");
		suburbs.add("Gaziler");
		citySuburbMap.put("Tuzluca", suburbs);
		stateCityMap.put("Iğdır", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Mustafakemalpaşa");
		suburbs.add("Bağlarbaşı");
		suburbs.add("Gacik");
		suburbs.add("Kadıköy");
		citySuburbMap.put("Yalova", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Altınova");
		suburbs.add("Kaytazdere");
		suburbs.add("Subaşı");
		suburbs.add("Tavşanlı");
		citySuburbMap.put("Altınova", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Armutlu");
		citySuburbMap.put("Armutlu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çiftlikköy");
		suburbs.add("Kılıç");
		suburbs.add("Taşköprü");
		citySuburbMap.put("Çiftlikköy", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Çınarcık");
		suburbs.add("Esenköy");
		suburbs.add("Koruköy");
		suburbs.add("Teşvikiye");
		citySuburbMap.put("Çınarcık", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Termal");
		suburbs.add("Akköy");
		citySuburbMap.put("Termal", suburbs);
		stateCityMap.put("Yalova", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Karabük Merkez");
		suburbs.add("5000 Evler");
		suburbs.add("100. Yıl");
		suburbs.add("Küçüksanayi");
		suburbs.add("Fevziçakmak");
		suburbs.add("Yenişehir");
		citySuburbMap.put("Karabük", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Eflani");
		citySuburbMap.put("Eflani", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Eskipazar");
		citySuburbMap.put("Eskipazar", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Ovacik");
		citySuburbMap.put("Ovacik", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Safranbolu Merkez");
		suburbs.add("Ovacuma");
		suburbs.add("Yazıköy");
		suburbs.add("Toprakcuma");
		suburbs.add("Konari");
		suburbs.add("Bostanbükü");
		citySuburbMap.put("Safranbolu", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Yenice");
		suburbs.add("Yortanpazarı");
		citySuburbMap.put("Yenice", suburbs);
		stateCityMap.put("Karabük", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Kilis Merkez");
		citySuburbMap.put("Kilis", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Elbeyli");
		citySuburbMap.put("Elbeyli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Musabeyli");
		citySuburbMap.put("Musabeyli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Polateli");
		citySuburbMap.put("Polateli", suburbs);
		stateCityMap.put("Kilis", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Osmaniye Merkez");
		suburbs.add("Fatih");
		suburbs.add("Gebeli Aslanlar");
		suburbs.add("Yunusemre");
		suburbs.add("Kaypak Serdar");
		suburbs.add("Tecirli Değirmenocağı");
		suburbs.add("Cevdetiye");
		suburbs.add("Yarpuz");
		citySuburbMap.put("Osmaniye", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Bahçe");
		citySuburbMap.put("Bahçe", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Düziçi");
		suburbs.add("Atalan");
		suburbs.add("Ellek");
		suburbs.add("Böcekli Boyalı");
		suburbs.add("Yarbaşi");
		citySuburbMap.put("Düziçi", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Hasanbeyli");
		citySuburbMap.put("Hasanbeyli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Dere");
		suburbs.add("Cemalpaşa");
		citySuburbMap.put("Kadirli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Sumbas");
		citySuburbMap.put("Sumbas", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("");
		suburbs.add("Toprakkale");
		suburbs.add("Tüysüz");
		citySuburbMap.put("Toprakkale", suburbs);
		stateCityMap.put("Osmaniye", citySuburbMap);
		citySuburbMap = new LinkedHashMap<String, List<String>>();
		suburbs = new ArrayList<String>();
		suburbs.add("");
		citySuburbMap.put("", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Düzce Merkez");
		suburbs.add("Aziziye - Günlü");
		suburbs.add("Azmimilli - Çay");
		suburbs.add("Beyciler");
		suburbs.add("Kalıcıkonutlar");
		suburbs.add("Beyköy");
		suburbs.add("Konuralp");
		suburbs.add("Boğaziçi");
		citySuburbMap.put("Düzce", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Akçakoca");
		citySuburbMap.put("Akçakoca", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Cumayeri");
		citySuburbMap.put("Cumayeri", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Çilimli");
		citySuburbMap.put("Çilimli", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Gölyaka");
		citySuburbMap.put("Gölyaka", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Gümüşova");
		citySuburbMap.put("Gümüşova", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Kaynaşlı");
		citySuburbMap.put("Kaynaşlı", suburbs);
		suburbs = new ArrayList<String>();
		suburbs.add("Yığılca");
		citySuburbMap.put("Yığılca", suburbs);
		stateCityMap.put("Düzce", citySuburbMap);

	}

}
